image: gitpod/workspace-postgres
tasks:
  - init: cp .env-sample .env && pipenv install --dev && pipenv run flask init-db
    command: pipenv run ./run.py
  - command: echo "Waiting venv creation..." && sleep 10 && pipenv shell
    openMode: split-right
ports:
  - port: 5000
    onOpen: ignore
